### ISSUE TITLE
[node] yarn config - Error: Cannot find module '/app/bin/../lib/cli'

### ISSUE THREAD

**Issue by Arxcis** [flatpak/flatpak-builder-tools#101]
### Hey! :)
I am currently working on a PR to Flathub -> https://github.com/flathub/flathub/pull/1406
Here is the app I am trying to build https://github.com/uw-labs/bloomrpc

I got a review that I should use the `flatpak-builder-tools` for building from source with `yarn` and `node`. I have written almost copy paste from the example `node/webpack-quick-start`.

I understand that I am missing `/app/lib/cli`, but I don't understand why.
 Any help would be greatly appreciated. Thanks :) 

### Manifest
```yaml
app-id: com.github.uwlabs.BloomRPC
runtime: org.freedesktop.Platform
runtime-version: '19.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '19.08' 
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node12
command: run
separate-locales: false
finish-args:
  - --share=ipc
  - --socket=x11
  - --share=network
  - --filesystem=home  
modules:
  - name: yarn
    sources:
      - type: archive
        url: https://github.com/yarnpkg/yarn/archive/v1.22.4.tar.gz
        sha256: f9e09bf375388f489a62a08d6ab0a455ab47d62b32512b35e4315d12d12db4e5
    buildsystem: simple
    build-commands:
      - 'cp -a * /app'
    cleanup:
      - '*'
  
  - name: bloomrpc
    sources:
      - type: git
        url: http://github.com/uw-labs/bloomrpc
        commit: afe9e60be6248be62c511d71d93fb25518d2e374
      - generated-sources.json
      - type: script
        dest-filename: run.sh
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/BloomRPC/bloomrpc
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/node12/bin:/app/yarn/bin:/run/build/bloomrpc/flatpak-node/chromedriver'
      env:
        ELECTRON_CACHE: /run/build/bloomrpc/flatpak-node/electron-cache
        CHROMEDRIVER_SKIP_DOWNLOAD: 'true'
        npm_config_nodedir: /usr/lib/sdk/node12
    build-commands:
      - HOME=$PWD yarn config --offline set yarn-offline-mirror $FLATPAK_BUILDER_BUILDDIR/flatpak-node/yarn-mirror
      - yarn --offline
      - sh flatpak-node/electron-builder-arch-args.sh
      - yarn run --offline package -- $ELECTRON_BUILDER_ARCH_ARGS
      # Max icon size for Flatpaks are 512x512. Having bigger icons results in build error
      - rm -rf build/files/share/icons/hicolor/1024x1024 
      - cp -r build/files/* $FLATPAK_DEST
      - install -Dm 755 run.sh $FLATPAK_DEST/bin/run
```

### Output
```
$ flatpak-builder --repo=.localrepo --force-clean build com.github.uwlabs.BloomRPC.yaml
Emptying app dir 'build'
Downloading sources
warning: redirecting to https://github.com/uw-labs/bloomrpc/
Fetching git repo http://github.com/uw-labs/bloomrpc, ref refs/tags/1.4.1
warning: redirecting to https://github.com/uw-labs/bloomrpc/
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Starting build of com.github.uwlabs.BloomRPC
Cache miss, checking out last cache hit
========================================================================
Building module yarn in /home/jonas/git/github/Arxcis/flathub/.flatpak-builder/build/yarn-1
========================================================================
Running: cp -a * /app
fusermount: failed to unmount /home/jonas/git/github/Arxcis/flathub/.flatpak-builder/rofiles/rofiles-eGmV6n: Device or resource busy
Committing stage build-yarn to cache
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
========================================================================
Building module bloomrpc in /home/jonas/git/github/Arxcis/flathub/.flatpak-builder/build/bloomrpc-4
========================================================================
Note: checking out 'afe9e60be6248be62c511d71d93fb25518d2e374'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at afe9e60 v1.4.1 (#168)
Running: HOME=$PWD yarn config --offline set yarn-offline-mirror $FLATPAK_BUILDER_BUILDDIR/flatpak-node/yarn-mirror
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module '/app/bin/../lib/cli'
Require stack:
- /app/bin/yarn.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/bin/yarn.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/bin/yarn.js' ]
}
Error: module bloomrpc: Child process exited with code 1
make: *** [Makefile:2: build] Error 1
```
