### ISSUE TITLE
[node] yarn --offline - node ./download-chromedriver.js - Error: getaddrinfo EAI_AGAIN github.com

### ISSUE THREAD

**Issue by Arxcis** [flatpak/flatpak-builder-tools#103]
**About**
Hi! I am trying to package **BloomRPC** https://github.com/uw-labs/bloomrpc.
Here is my PR on `flathub` https://github.com/flathub/flathub/pull/1406
I have looked for existing issues like this, but I did not find any.

**Build options**
```yaml
  - name: bloomrpc
    sources:
      - type: git
        url: http://github.com/uw-labs/bloomrpc
        commit: '1.4.1'
      - generated-sources.json
      - type: script
        dest-filename: run.sh
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/BloomRPC/bloomrpc
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/node12/bin:/app/yarn/bin:$FLATPAK_BUILDER_BUILDDIR/flatpak-node/chromedriver
      env:
        ELECTRON_CACHE: /run/build/bloomrpc/flatpak-node/electron-cache
        CHROMEDRIVER_SKIP_DOWNLOAD: 'true'
        npm_config_nodedir: /usr/lib/sdk/node12
    build-commands:
      - HOME=$PWD yarn config --offline set yarn-offline-mirror $FLATPAK_BUILDER_BUILDDIR/flatpak-node/yarn-mirror
      - yarn --offline
      - sh flatpak-node/electron-builder-arch-args.sh
      - yarn run --offline package -- $ELECTRON_BUILDER_ARCH_ARGS
      # Max icon size for Flatpaks are 512x512. Having bigger icons results in build error
      - rm -rf build/files/share/icons/hicolor/1024x1024
      - cp -r build/files/* $FLATPAK_DEST
      - install -Dm 755 run.sh $FLATPAK_DEST/bin/run
```
**Output** 
```
➜  flathub git:(com.github.uwlabs.BloomRPC) ✗  flatpak-builder --repo=.localrepo --force-clean build com.github.uwlabs.BloomRPC.yaml
Emptying app dir 'build'
Downloading sources
warning: redirecting to https://github.com/uw-labs/bloomrpc/
Fetching git repo http://github.com/uw-labs/bloomrpc, ref refs/tags/1.4.1
warning: redirecting to https://github.com/uw-labs/bloomrpc/
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Starting build of com.github.uwlabs.BloomRPC
Cache hit for yarn, skipping build
Cache miss, checking out last cache hit
========================================================================
Building module bloomrpc in /home/jonas/git/github/Arxcis/flathub/.flatpak-builder/build/bloomrpc-11
========================================================================
Note: checking out '1.4.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at afe9e60 v1.4.1 (#168)
Running: HOME=$PWD yarn config --offline set yarn-offline-mirror $FLATPAK_BUILDER_BUILDDIR/flatpak-node/yarn-mirror
yarn config v1.22.4
success Set "yarn-offline-mirror" to "/run/build/bloomrpc/flatpak-node/yarn-mirror".
Done in 0.04s.
Running: yarn --offline
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-sortable-hoc@1.9.1" has unmet peer dependency "prop-types@^15.5.7".
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.3.0" has unmet peer dependency "jest-resolve@^24.1.0".
warning "jest > jest-cli > jest-config > jest-resolve@24.3.0" has unmet peer dependency "jest-haste-map@^24.0.0".
[4/4] Building fresh packages...
[-/5] ⢀ waiting...
[2/5] ⢀ electron
[-/5] ⢀ waiting...
[4/5] ⢀ node-sass
error /run/build/bloomrpc/node_modules/electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments: 
Directory: /run/build/bloomrpc/node_modules/electron-chromedriver
Output:
/run/build/bloomrpc/node_modules/electron-chromedriver/download-chromedriver.js:19
  if (err != null) throw err
                   ^

Error: getaddrinfo EAI_AGAIN github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',




^[[A^Cmake: *** [Makefile:11: build] Interrupt

```

**Thoughts**

- Clearly `yarn --offline` tries to install `electron-chromedriver` which in turn tries to run `node ./download-chromedriver.js` and this fails because it's offline, right?
 - I thought setting `CHROMEDRIVER_SKIP_DOWNLOAD='true'` would fix this, but there is no difference.
- Here is the line in `electron-chromedriver` that `throws` in the output above - https://github.com/electron/chromedriver/blob/master/download-chromedriver.js#L19
- It catches an error from a callback function which is returned from another package, `electron-download`. Here is the npm package https://www.npmjs.com/package/electron-download, but the github-link redirects me to `electron/get` which has different source code. Maybe `electron-download` does not exist on github anymore.
