### ISSUE TITLE
getaddrinfo EAI_AGAIN github.com in electron@11.0.3~postinstall

### ISSUE THREAD

**Issue by xcffl** [flatpak/flatpak-builder-tools#173]
I generated a `generated-sources.json` for https://github.com/yang991178/fluent-reader, and wrote the build yaml as per the sample. But when it runs `'npm install --offline --prefix=fluent-reader --verbose --cache=$FLATPAK_BUILDER_BUILDDIR/flatpak-node/npm-cache'`, it raises an error:

```
npm info lifecycle electron@11.0.3~postinstall: electron@11.0.3

> electron@11.0.3 postinstall /run/build/fluent-reader/fluent-reader/node_modules/electron
> node install.js

RequestError: getaddrinfo EAI_AGAIN github.com
    at ClientRequest.<anonymous> (/run/build/fluent-reader/fluent-reader/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/run/build/fluent-reader/fluent-reader/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm verb lifecycle electron@11.0.3~postinstall: unsafe-perm in lifecycle true
```

The build yaml file:

```yaml
app-id: me.hyliu.fluentreader
runtime: org.freedesktop.Platform
runtime-version: "20.08"
branch: stable
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: 20.08
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node14
command: fluent-reader
separate-locales: false
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --share=network
modules:
  # First step is to install Node to /app/node, that way it can be accessible outside of the sdk
  # environment. install-sdk.sh is used because install.sh omits npm.
  # (This does not need to be done for electron-builder, see
  # electron-webpack-quick-start's build.electron.webpack.ElectronWebpackQuickStart.yaml for an
  # explanation.)
  # - name: node
  #   buildsystem: simple
  #   build-commands:
  #     - '/usr/lib/sdk/node14/install-sdk.sh'

  # Now is the quickstart module.
  - name: fluent-reader
    buildsystem: simple
    build-options:
      # Add the node bin directory.
      append-path: /usr/lib/sdk/node14/bin
      env:
        # Set the Electron cache directory.
        # (The directory format is: /run/build/MODULE_NAME/flatpak-node/electron-cache)
        ELECTRON_CACHE: '/run/build/fluent-reader/flatpak-node/electron-cache'
        # Sets the directory where Node is located so way npm won't download the headers.
        npm_config_nodedir: '/usr/lib/sdk/node14'
    build-commands:
      # Have Yarn use the offline mirror.
      - 'npm install --offline --prefix=fluent-reader --verbose --cache=$FLATPAK_BUILDER_BUILDDIR/flatpak-node/npm-cache'
      # Download the packages.
      # If you were using npm with electron-webpack/electron-builder, then the above two commands
      # would look more like the npm commands in the vanilla-quick-start manifest, just without
      # the --prefix.

      # Run electron-builder, passing the architecture arguments to it.
      # Note that the -- is important; without that, the argument will be passed to
      # yarn instead of electron-builder.
      - ". flatpak-node/electron-builder-arch-args.sh; npm run --prefix=fluent-reader --offline package-linux -- $ELECTRON_BUILDER_ARCH_ARGS"
      # Copy the resulting, unpacked directory to /app.
      # (A glob is used because the directory name may contain the current arch.)
      - "cp -r bin/linux*unpacked /app/fluent-reader"
      # If you passed --electron-non-patented-ffmpeg, you could install it like this:
      # - 'install -Dm 755 flatpak-node/libffmpeg.so -t /app/electron-webpack-quick-start'
      # Install the wrapper script to start it.
      - "install -Dm 755 start-fluent-reader.sh /app/bin/start-fluent-reader"
    sources:
      - type: git
        url: https://github.com/yang991178/fluent-reader
        # Use the Electron 4 / Node 10 version.
        commit: master
        # Checkout into a subdirectory so we can copy the whole thing to /app.
        dest: fluent-reader
      # Add the flatpak-node-generator generated sources.
      - generated-sources.json
      # Our runner script.
      - type: script
        dest-filename: start-fluent-reader.sh
        commands:
          - 'export PATH=$PATH:/app/node/bin'
          - 'npm start --prefix=/app/fluent-reader'
```
