### ISSUE TITLE
pip-gen: Exception: Failed to get PyQt5 source

### ISSUE THREAD

**Issue by prateekmedia** [flatpak/flatpak-builder-tools#239]
I have tried this 10th time but still same error, I want `pyqt5` as an requirement to build [Persepolis flatpak](https://github.com/flathub/flathub/pull/2553), but It is failing at the below output, For `pyside2` or `pyside6` see https://github.com/flatpak/flatpak-builder-tools/issues/239#issuecomment-972819353, I haven't updated the logs but the error is same for `pyqt5`:
```
Exception: Failed to get PySide2-5.15.2 source from https://pypi.org/pypi/PySide2/5.15.2/json
```

**Python version**: `3.9.7`
**OS**: `Pop!_OS 21.10`

<details>
<summary>
requirements.txt
</summary>

```
pyside2
requests
setproctitle
psutil
youtube-dl
```
</details>

<details>
<summary>
Command
</summary>

```
./flatpak-pip-generator --requirements-file=requirements.txt --output pypi-dependencies
```
</details>

<details>
<summary>
Full Output
</summary>

```
Downloading sources
========================================================================
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-pypi-dependenciesi7if8x0g -r requirements.txt"
Collecting pyside2
  Using cached PySide2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl (164.3 MB)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting setproctitle
  Using cached setproctitle-1.2.2-cp39-cp39-manylinux1_x86_64.whl (35 kB)
Collecting psutil
  Using cached psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl (293 kB)
Collecting youtube-dl
  Using cached youtube_dl-2021.6.6-py2.py3-none-any.whl (1.9 MB)
Collecting shiboken2==5.15.2
  Using cached shiboken2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl (956 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/PySide2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/shiboken2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/requests-2.26.0-py2.py3-none-any.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/certifi-2021.10.8-py2.py3-none-any.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/charset_normalizer-2.0.7-py3-none-any.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/idna-3.3-py3-none-any.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/urllib3-1.26.7-py2.py3-none-any.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/setproctitle-1.2.2-cp39-cp39-manylinux1_x86_64.whl
Saved /tmp/pip-generator-pypi-dependenciesi7if8x0g/youtube_dl-2021.6.6-py2.py3-none-any.whl
Successfully downloaded psutil pyside2 shiboken2 requests certifi charset-normalizer idna urllib3 setproctitle youtube-dl
========================================================================
Downloading arch independent packages
========================================================================
Deleting psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl
Downloading https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz
Traceback (most recent call last):
  File "/media/prateeksu/C8409541409536E2/Projects/temp/persepolis/./flatpak-pip-generator", line 232, in <module>
    url = get_tar_package_url_pypi(name, version)
  File "/media/prateeksu/C8409541409536E2/Projects/temp/persepolis/./flatpak-pip-generator", line 68, in get_tar_package_url_pypi
    raise Exception(err)
Exception: Failed to get PySide2-5.15.2 source from https://pypi.org/pypi/PySide2/5.15.2/json
```
</details>

**Comment by DavidoTek** [comment]
Same problem here, seems like flatpak-pip-generator expects the package to be available as a source archive, not a Python wheel. PySide is not available as an archive from pypi.
https://github.com/flatpak/flatpak-builder-tools/blob/c1b2458f6df7c4ec8d5df5b00bdcaa026a1b67b9/pip/flatpak-pip-generator#L63,

**Comment by lpyparmentier** [comment]
Hello, I'm stuck with the same trouble, i'm trying to build a flatpak package for streamdeck-ui, which requires PySide :(

**Comment by lpyparmentier** [comment]
I've try to fix this by mixing a lot of things, but it becomes to tricky and very ugly, it will even work at a time but it would be unmaintainable. In case someone is interesting to go forward or to help me here is some steps i've been through:
1. using ork.kde.Platform runtime (looks more adapted for pyside2)
2. add pyside and build it thanks to cmake-ninja (inspired from [FreeCAD] (https://github.com/flathub/org.freecadweb.FreeCAD/blob/master/org.freecadweb.FreeCAD.yaml))
3. I had to include poetry dependencies (due to the flatpak build tools pip+poetry not able to get it from streamdeck) `wget https://github.com/python-poetry/poetry/blob/master/poetry.lock && flatpak-poetry-generator.py poetry.lock`
4. I manually added setuptools and wheels in `generated-poetry-sources.json` (followed [this idea](https://github.com/flatpak/flatpak-builder-tools/issues/90#issuecomment-650902678))
5. give up time, too much tricky gives an error like `https://github.com/flatpak/flatpak-builder-tools/issues/90#issuecomment-650902678` when building

so far streamdeck.yml:
```yaml
app-id: io.parmentier.flatpak.streamdeck-ui
runtime: org.kde.Platform
runtime-version: '5.15'
sdk: org.kde.Sdk
command: streamdeck
modules:
  - name: pyside2
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTS=OFF
    cleanup:
      - /bin
    sources:
      - type: archive
        url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.15.2-src/pyside-setup-opensource-src-5.15.2.tar.xz
        sha256: b306504b0b8037079a8eab772ee774b9e877a2d84bab2dbefbe4fa6f83941418
      - type: shell
        commands:
          - mkdir -p /app/include/qt5tmp && cp -R /usr/include/Qt* /app/include/qt5tmp # https://bugreports.qt.io/browse/PYSIDE-787
          - sed -i 's|\(--include-paths=\)|\1/app/include/qt5tmp:|' sources/pyside2/cmake/Macros/PySideModules.cmake
  - generated-poetry-sources.json
  - name: python3-poetry
    buildsystem: simple
    build-commands:
      - pip3 install --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} poetry
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/57/93/30798f4df5633eaae1de4d851428fa72d281f949366c116eb21ed41530c5/poetry-1.1.11.tar.gz
        sha256: 7d7d22f55fbebb830cc85b1c69cd7a91fd85f49e5396e7a14b953645a470f69e
 
  - name: streamdeck-ui
    buildsystem: simple
    build-commands:
      - pip3 install --prefix=/app .
    sources:
      - type: git
        url: https://github.com/timothycrosley/streamdeck-ui.git
        tag: v1.1.2

```

For now I give up, with my lack of knowledge I spend too much time not feeling that I look in the right direction to respect best practice and make it properly :)
