### ISSUE TITLE
flatpak-pip-generator does not add flit_core for pyparsing

### ISSUE THREAD

**Issue by MehdiChinoune** [flatpak/flatpak-builder-tools#269]
When trying to generate build steps for pyparsing, It does not include `flit_core` which is required to build pyparsing:
```
$ ./flatpak-pip-generator --cleanup all --yaml --checker-data --output python3-pyarsing pyparsing
========================================================================
Downloading sources
========================================================================
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python3-pyarsing7nccz9zs -r /tmp/requirements.48azufw7"
Collecting pyparsing
  Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
Saved /tmp/pip-generator-python3-pyarsing7nccz9zs/pyparsing-3.0.8-py3-none-any.whl
Successfully downloaded pyparsing
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
========================================================================
Downloading arch independent packages
========================================================================
========================================================================
Obtaining hashes and urls
========================================================================
Generating hash for pyparsing-3.0.8-py3-none-any.whl
Extracting download url for pyparsing
========================================================================
Generating dependencies
========================================================================
Generating dependencies for pyparsing
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

Output saved to python3-pyarsing.yaml
```
python3-pyparsing.yaml:
```yaml
name: python3-pyparsing
buildsystem: simple
build-commands:
  - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
    --prefix=${FLATPAK_DEST} "pyparsing" --no-build-isolation
sources:
  - type: file
    url: https://files.pythonhosted.org/packages/d9/41/d9cfb4410589805cd787f8a82cddd13142d9bf7449d12adf2d05a4a7d633/pyparsing-3.0.8-py3-none-any.whl
    sha256: ef7b523f6356f763771559412c0d7134753f037822dad1b16945b7b846f7ad06
    x-checker-data:
      name: pyparsing
      packagetype: bdist_wheel
      type: pypi
cleanup:
  - '*'
```
