### ISSUE TITLE
perl-libs/install.sh has the wrong prefix

### ISSUE THREAD

**Issue by Mailaender** [flatpak/flatpak-builder-tools#273]
### flatpak-builder version

1.0.9

### Linux distribution and version

openSUSE 15.3

### Affected flatpak-builder tool

cpan/flatpak-cpan-generator.pl

### Description

`./flatpak-cpan-generator.pl Modern::Perl`

```yaml
modules:
  - name: perl-libs
    buildsystem: simple
    build-commands:
      - 'perl-libs/install.sh'
    # Same as with the Perl module, we need to restore write permission.
    # However, -f is now passed to avoid errors from trying to touch files from the
    # above module that are now marked as read-only.
    post-install:
      - 'chmod -Rf u+w /app/lib/perl5/site_perl'
    sources:
      - generated-sources.json
    # This step should be customized based on the CPAN packages you're using.
    cleanup:
      - '/bin'
      - '/man'
```

results in 

```
Running: perl-libs/install.sh
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Modern::Perl
Writing MYMETA.yml and MYMETA.json
cp lib/odern/Perl.pm blib/lib/odern/Perl.pm
cp lib/Modern/Perl.pm blib/lib/Modern/Perl.pm
Manifying 2 pod documents
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/usr/lib/perl5/site_perl/5.34.0/Modern'
mkdir /usr/lib/perl5/site_perl/5.34.0/Modern: Read-only file system at /usr/lib/perl5/5.34.0/ExtUtils/Install.pm line 470.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
make: *** [Makefile:732: pure_site_install] Error 30
```
