### ISSUE TITLE
Fail to generate pygments, empty build script and url.

### ISSUE THREAD

**Issue by kevinsmia1939** [flatpak/flatpak-builder-tools#275]
### flatpak-builder version

1.2.2

### Linux distribution and version

openSUSE Tumbleweed

### Affected flatpak-builder tool

pip/flatpak-pip-generator

### Description

Using the command,

```
andy@localhost:~/Desktop/Flatpak/flatpak-builder-tools/pip> python3 flatpak-pip-generator pygments
========================================================================
Downloading sources
========================================================================
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python3-pygments06atwtdr -r /tmp/requirements.8uj7obyi"
Collecting pygments
  Using cached Pygments-2.12.0-py3-none-any.whl (1.1 MB)
Saved /tmp/pip-generator-python3-pygments06atwtdr/Pygments-2.12.0-py3-none-any.whl
Successfully downloaded pygments
========================================================================
Downloading arch independent packages
========================================================================
========================================================================
Obtaining hashes and urls
========================================================================
Generating hash for Pygments-2.12.0-py3-none-any.whl
Extracting download url for Pygments
========================================================================
Generating dependencies
========================================================================

Output saved to python3-pygments.json
```
Will result in the following empty manifest.

```
{
    "name": "python3-pygments",
    "buildsystem": "simple",
    "build-commands": [],
    "modules": []
}
```

**Comment by JakobDev** [comment]
Pygments is alraedy included in the SDK, so  it's blacklisted in flatpak-pip-generator. To use it in your App without using the SDK as Runtime, try this:
```yaml
  - name: pygments
    buildsystem: simple
    build-commands:
      - mkdir -p /app/lib/python3.9/site-packages
      - cp -r /usr/lib/python3.9/site-packages/pygments /app/lib/python3.9/site-packages
      - cp -r /usr/lib/python3.9/site-packages/Pygments-*.egg-info /app/lib/python3.9/site-packages
```
