### ISSUE TITLE
Support for Go modules?

### ISSUE THREAD

**Issue by yktoo** [flatpak/flatpak-builder-tools#285]
### flatpak-builder version

1.2.2

### Linux distribution and version

Ubuntu 22.04

### Affected flatpak-builder tool

go-get/flatpak-go-vendor-generator.py

### Source repository URL

https://github.com/yktoo/ymuse

### Flatpak-builder manifest URL

https://github.com/flathub/flathub/pull/3226

### Description

This tool (or its README) doesn't seem to support Go modules. I'm trying to follow the README given this manifest:

```yaml
[skipped]
modules:
  - name: ymuse
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/golang/bin
      env:
        GOBIN: /app/bin
        GOPATH: /run/build/ymuse
      build-args:
        - --share=network
    build-commands:
      - go get ./...
      - go generate
      - go build -ldflags "-s -w -X main.version=$(git describe --always --tags) -X main.commit=$(git rev-parse HEAD) -X main.date=$(git log -1 --format=%cd --date=iso-strict)"
      # [...skipped...]
    sources:
      - type: git
        url: https://github.com/yktoo/ymuse
        tag: v0.20
```

When trying to build it I get:

```
Running: go get ./...
$GOPATH/go.mod exists but should not
Error: module ymuse: Child process exited with code 1
```
