### ISSUE TITLE
Cargo.toml not found

### ISSUE THREAD

**Issue by elpiel** [flatpak/flatpak-builder-tools#344]
### flatpak-builder version

1.0.10

### Linux distribution and version

Ubuntu 20.04

### Affected flatpak-builder tool

cargo/flatpak-cargo-generator.py

### Description

Based on the quickstart template I'm trying to build an app using a `buildsystem: simple`, the problem, however, is that every time it gets to the `build-commands` it returns an error that the `Cargo.toml` file is not found...

```
Running: cargo --offline fetch --manifest-path Cargo.toml --verbose
error: manifest path `Cargo.toml` does not exist
```

My manifest looks like this:

```
My manifest is in the root of the project:

app-id: com.........
runtime: org.gnome.Platform
runtime-version: "43"
sdk: "org.gnome.Sdk"
sdk-extensions:
  - org.freedesktop.Sdk.Extension.rust-stable
command: my-app-service
finish-args:
  - --share=network
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --talk-name=org.kde.StatusNotifierWatcher
build-options:
  append-path: /usr/lib/sdk/rust-stable/bin
modules:
  - name: service
    buildsystem: simple
    build-options:
      env:
        # - RUSTFLAGS: '--remap-path-prefix =../'
        - CARGO_HOME: /run/build/service/cargo
    build-commands:
      # - echo $(pwd)
      # - ls -la .
      # - ls -la ../
      # - ls -la ../../
      # - ls -la ../../../
      - cargo --offline fetch --manifest-path Cargo.toml --verbose
      - cargo --offline build --release --features=bundled --verbose
    post-install:
      - install -Dm755 target/release/my-app-service -t /app/bin/my-app-service/
      - install -Dm644 flatpak/com..........desktop /app/share/applications/com..........desktop
      - install -Dm644 flatpak/com..........svg /app/share/icons/hicolor/scalable/apps/com..........svg
      - install -Dm644 flatpak/com..........appdata.xml /app/share/metainfo/com..........xml
    sources:
      - type: dir
        path: "."
        # path: "../" # tried with RUSTFLAGS too
      - generated-sources.json # The file from the generator
    modules:
      - flatpak/shared-modules/libappindicator/libappindicator-gtk3-12.10.json # submodule
```
