### ISSUE TITLE
ENOTCACHED error even though the package is cached

### ISSUE THREAD

**Issue by suntorytimed** [flatpak/flatpak-builder-tools#439]
### flatpak-builder version

1.4.4

### Linux distribution and version

openSUSE Tumbleweed

### Affected flatpak-builder tool

npm/flatpak-npm-generator.py

### flatpak-builder tool cli args

--user --install --force-clean

### Source repository URL

https://github.com/camunda/camunda-modeler

### Flatpak-builder manifest URL

https://github.com/suntorytimed/flathub/tree/io.github.camunda.camunda-modeler

### Description

Even though `webpack-sources` is part of the `generated-sources.json` and is in the cache the `npm install --offline` still fails with:
```
npm error code ENOTCACHED
npm error request to https://registry.npmjs.org/webpack-sources failed: cache mode is 'only-if-cached' but no cached response is available.
```

**Comment by Fredolx** [comment]
I'm having the same issue.

```
Running: npm install --offline --verbose
npm verbose cli /usr/lib/sdk/node20/bin/node /usr/lib/sdk/node20/bin/npm
npm info using npm@10.8.2
npm info using node@v20.19.4
npm verbose title npm install
npm verbose argv "install" "--offline" "--loglevel" "verbose"
npm verbose logfile logs-max:10 dir:/run/build/opentv/flatpak-node/npm-cache/_logs/2025-07-20T00_06_10_278Z-
npm verbose logfile /run/build/opentv/flatpak-node/npm-cache/_logs/2025-07-20T00_06_10_278Z-debug-0.log
npm http fetch GET https://registry.npmjs.org/npm attempt 1 failed with EAI_AGAIN
npm verbose stack Error: request to https://registry.npmjs.org/@tauri-apps%2fplugin-clipboard-manager failed: cache mode is 'only-if-cached' but no cached response is available.
npm verbose stack     at cacheFetch (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
npm verbose stack     at async fetch (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
npm verbose stack     at async RegistryFetcher.packument (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/pacote/lib/registry.js:90:19)
npm verbose stack     at async RegistryFetcher.manifest (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/pacote/lib/registry.js:128:23)
npm verbose stack     at async #fetchManifest (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1199:20)
npm verbose stack     at async #nodeFromEdge (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1037:19)
npm verbose stack     at async #buildDepStep (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
npm verbose stack     at async Arborist.buildIdealTree (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
npm verbose stack     at async Promise.all (index 1)
npm verbose stack     at async Arborist.reify (/usr/lib/sdk/node20/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
npm error code ENOTCACHED
npm error request to https://registry.npmjs.org/@tauri-apps%2fplugin-clipboard-manager failed: cache mode is 'only-if-cached' but no cached response is available.
npm verbose cwd /run/build/opentv
npm verbose os Linux 6.15.5-200.fc42.x86_64
npm verbose node v20.19.4
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: /run/build/opentv/flatpak-node/npm-cache/_logs/2025-07-20T00_06_10_278Z-debug-0.log
Error: module opentv: Child process exited with code 1
```
`plugin-clipboard-manager` is present in the cache.

This is my manifest
```
 - name: opentv
      buildsystem: simple
      build-options:
          env:
              XDG_CACHE_HOME: /run/build/opentv/flatpak-node/cache
              npm_config_cache: /run/build/opentv/flatpak-node/npm-cache
              npm_config_offline: "true"
              CARGO_HOME: /run/build/opentv/cargo
      sources:
          - type: git
            url: https://github.com/Fredolx/open-tv
            commit: 42ee129684660a0db900c674000170d78fc81144
            tag: v1.8.0
          - generated-sources.json
          - cargo-sources.json
      build-commands:
          - npm install --offline --verbose
          - cargo --offline fetch --manifest-path src-tauri/Cargo.toml --verbose
          - npm run tauri build -- --no-bundle
```

I've also tried yarn with no success.

I've ran
```
npm install --package-lock-only 
#or      
npm install --package-lock-only --lockfile-version 2 
flatpak-node-generator npm ../open-tv/package-lock.json --no-requests-cache -o generated-sources.json
flatpak run org.flatpak.Builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir dev.fredol.open-tv.yaml 
```

One of the entries in generated-sources.json
```
    {
        "type": "file",
        "url": "https://registry.npmjs.org/@tauri-apps/plugin-clipboard-manager/-/plugin-clipboard-manager-2.3.0.tgz",
        "sha512": "f3534e040d8ff8e4d8f112e4070ca5f5947fd027a080bb9be05eb3c5cc5421f14e02ab64cbb27ad7e2bf3241f6482d45331341c6b5f4b300ee2af92390769d94",
        "dest-filename": "4e040d8ff8e4d8f112e4070ca5f5947fd027a080bb9be05eb3c5cc5421f14e02ab64cbb27ad7e2bf3241f6482d45331341c6b5f4b300ee2af92390769d94",
        "dest": "flatpak-node/npm-cache/_cacache/content-v2/sha512/f3/53"
    },
```
